experiment-name: first-01
training-dataset: /mnt/g/stockfish-data/dfrc99-16tb7p-eval-filt-v2.min.binpack
nnue-pytorch-branch: Disservin/nnue-pytorch/uv

early-fen-skipping: 28
num-epochs: 800
start-lambda: 1.0
end-lambda: 0.7
network-testing-games-per-round: 1000
network-testing-threads: 24
num-workers: 6
start-from-engine-test-net: True

lr: 4.375e-4
gamma: 0.995

build-engine-arch: x86-64-bmi2
workspace-path: ./testing
gpus: 0
# nnue_pytorch_directory: ./src/nnue_pytorch
features: HalfKAv2_hm^
